pipeline {
  agent {
    node {
      label 'nodejs'
    }

  }
  stages {
    stage('拉取源代码') {
      steps {
        git(url: 'http://xxxx/xxxx.git', credentialsId: 'git-id', branch: 'master', changelog: true, poll: false)
        sh '''cat > Dockerfile <<EOF
FROM nginx:latest
RUN mkdir /home/html
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
COPY h5.conf /etc/nginx/conf.d/h5.conf
COPY dist/  /home/html/
EXPOSE 80

EOF
'''
        sh '''cat > h5.yml <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: h5-frontend-prod
  namespace: app
  labels:
    app: h5-frontend-prod
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: h5-frontend-prod
  template:
    metadata:
      labels:
        app: h5-frontend-prod
    spec:
      imagePullSecrets:
        - name: images-registry-id
      containers:
        - name: h5-frontend-prod
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:PROD-$BUILD_NUMBER
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "300m"
              memory: "2048Mi"
          readinessProbe:
            periodSeconds: 10
            initialDelaySeconds: 10
            httpGet:
              port: http
              path: /
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 30
            httpGet:
              port: http
              path: /
          ports:
            - name: http
              containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: h5-frontend-prod
  name: h5-frontend-prod-svc
  namespace: app
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30110
  selector:
    app: h5-frontend-prod
  type: NodePort
  
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: h5-frontend-prod-hpa
  namespace: app
spec:
  minReplicas: 3
  maxReplicas: 12
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: h5-frontend-prod
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: memory
        targetAverageValue: 1700Mi
EOF
'''
      }
    }
    stage('构建并推送镜像') {
      steps {
        container('nodejs') {
          sh 'npm install'
          sh 'npm  run release'
          sh '''cat >h5.conf<<EOF

server {
   listen       80 default_server;
   server_name  _;
   gzip on;
   gzip_min_length  5k;
   gzip_buffers     4 16k;
   gzip_http_version 1.0;
   gzip_comp_level 3;
   gzip_types     image/jpeg image/gif image/png image/ico text/plain application/x-javascript text/css text/javascript application/apk  application/json;
   gzip_vary on;
   gzip_disable "MSIE [1-6].";
   charset utf-8;

   location / {
        root /home/html/;
        index  index.html index.htm;
        try_files \\$uri \\$uri/ /index.html;
   }


   location ~* ^/(v1) {
            rewrite ^/v1/(.+?)$ /\\$1 break; 
            proxy_pass       http://app-backend-prod-svc.app:8080;
            proxy_set_header Host      \\$host;
            proxy_set_header X-Real-IP \\$remote_addr;
            proxy_set_header X-Forwarded-For \\$proxy_add_x_forwarded_for;

   }
  location ~* ^/(v2) {
        rewrite ^/v2/(.+?)$ /\\$1 break; 
        proxy_pass       http://app-backend-prod-svc.app:8080;
        proxy_set_header Host \\$host;
        proxy_set_header X-Real-IP \\$remote_addr;
        proxy_set_header X-Forwarded-For \\$proxy_add_x_forwarded_for;
        proxy_redirect default;
        proxy_set_header Upgrade "websocket";
        proxy_set_header Connection "Upgrade";
        proxy_http_version 1.1;
        proxy_read_timeout 1200s;               
   }

   location ~ \\.(html|htm|gif|jpg|jpeg|bmp|png|ico|txt|js|css|woff|woff2|eot|otf|svg|ttf|psd|jade|less|scss|json|xls|xlsx)$ {
      root /home/html/;
   }

}

EOF'''
          sh 'docker build -f Dockerfile -t $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:PROD-$BUILD_NUMBER .'
          withCredentials([usernamePassword(credentialsId : 'registry-id' ,passwordVariable : 'DOCKER_PASSWORD' ,usernameVariable : 'DOCKER_USERNAME' ,)]) {
            sh 'echo "$DOCKER_PASSWORD" | docker login $REGISTRY -u "$DOCKER_USERNAME" --password-stdin'
            sh 'docker push $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:PROD-$BUILD_NUMBER'
          }

        }

      }
    }
    stage('发布到PROD环境') {
      steps {
        kubernetesDeploy(enableConfigSubstitution: true, deleteResource: false, kubeconfigId: 'kubeconfig-id', configs: 'h5.yml')
      }
    }
  }
    post {
        //任务失败执行
        failure {
          sh "wget --post-data 'content= 流水线执行失败 ' xxxx"
        }
        //任务成功后执行
        success {
          sh "wget --post-data 'content= 流水线执行成功 ' xxxxx"
        }    
    }
}
